<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="VramMonitor.Windows.Tests" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\VramMonitor.Core\VramMonitor.Core.csproj" />
  </ItemGroup>
</Project>
